### ISSUE TITLE
nnets?

### ISSUE THREAD

**Issue by hyiltiz** [lacerbi/ModelWork#1]
Does this suite integrates well with neural networks models in addition to ML models as well? More like a feature request for documentation, but let me just ask it here.

**Comment by lacerbi** [comment]
The framework is thought for projects which have multiple datasets (e.g. subjects), models, and trials, and models have a log likelihood (e.g. typical projects in psychophysics). If your neural networks give a prediction of subjects' behavior which can be converted in a LL then yes, otherwise _probably_ not, although of course anything can be hacked to make it work.

BTW the documentation for now is awful as this is a suite of functions I started building during my PhD, and it went through several iterations. The concept is that all projects have pretty much the same structure, so I can focus only on coding the core functions (e.g., model specification, log likelihood function), and a lot of other things are taken care of automatically. But in its current form it is not really thought for public usage -- although I am glad if you can find and reuse something from it.

**Comment by hyiltiz** [comment]
Yeah, I also feel that most of our projects share similar structure and abstracting those away and focusing on the project specific details is a very great idea. I also have a template project for behavior psychophysics experiment using Psychtoolbox. The experimenter only has to specify the experimental design and how the data should be analyzed. The rest is taken care of by the template. In some ways, it is similar to PsychoPy. So I really liked this idea for modeling as well.
I am playing around with Haskell for a while now, and libraries like this is prevalent in the Haskell community. Matlab is really a poor language of choice for us :(
